### ISSUE TITLE
Filtering expression feature roadmap/tracking

### ISSUE THREAD

**Issue by ypoluektovich** [ypoluektovich/wikitables#1]
Column value filtering:
- [x] Strict value comparison `=`
- [x] "Not equals" `!=`
- [x] Case insensitive comparison (probably using `=` and `!=`; strict versions will become `==` and `!==`)
- [ ] Regular expressions
- [ ] Greater, lesser, etc

Logical operators:
- [x] not
- [x] and
- [x] or
- [x] parentheses

Magic:
- [ ] Boolean cells detection
- [ ] Numeric cells detection
- [ ] Date/time cells detection
- [ ] Filtering over page sections
